site_name: vizta
repo_url: https://github.com/TalusBio/vizta
nav:
    - index.ipynb
    - api.md

theme:
  name: material
  favicon: static/talus-logo.svg
  logo: static/talus-logo.svg
  font:
    text: IBM Plex Sans
  features:
     - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://seaborn.pydata.org/objects.inv
          options:
            docstring_style: numpy
            show_root_heading: true
            heading_level: 3
            docstring_section_style: spacy
            show_source: false
            merge_init_into_class: true
  - mkdocs-jupyter:
      execute: true
