name: Push docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install font
        run: |
          tmpdir=$(mktemp -d)
          wget -q -O "$tmpdir/host-grotesk.zip" \
            "https://github.com/Element-Type/HostGrotesk/releases/download/1.002/HostGrotesk_v1.002.zip"
          unzip -q "$tmpdir/host-grotesk.zip" -d "$tmpdir"

          sudo mkdir -p /usr/local/share/fonts/host-grotesk
          sudo cp "$tmpdir"/*.ttf /usr/local/share/fonts/host-grotesk/

          sudo fc-cache -fv
          fc-match "Host Grotesk"
      - run: uv sync --group docs
      - run: uv run mkdocs gh-deploy --force
