name: Push docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install font
        run: |
          # Install Host Grotesk instead of Montserrat
          cd /usr/local/share/fonts
          wget -q https://github.com/Element-Type/HostGrotesk/releases/download/1.002/HostGrotesk_v1.002.zip -O host-grotesk.zip
          unzip -q host-grotesk.zip
          sudo chmod -R --reference=/usr/share/fonts/truetype HostGrotesk
          sudo fc-cache -fv
          fc-match "Host Grotesk"

      - run: uv sync --group docs
      - run: uv run mkdocs gh-deploy --force
