name: Push docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install font
        run: |
          # ---- Install Host Grotesk from Google Fonts ----
          sudo apt-get update -y
          sudo apt-get install -y wget unzip      # tar is no longer needed

          # 1) download the family ZIP
          tmp_dir=$(mktemp -d)
          cd "$tmp_dir"
          # Download the family ZIP (-L follows the redirect to fonts.gstatic.com)
          curl -L -o host-grotesk.zip \
            "https://fonts.google.com/download?family=Host+Grotesk"

          sudo mkdir -p /usr/share/fonts/truetype/hostgrotesk
          unzip -q host-grotesk.zip -d /usr/share/fonts/truetype/hostgrotesk
          sudo chmod -R --reference=/usr/share/fonts/truetype/dejavu \
               /usr/share/fonts/truetype/hostgrotesk

          # 3) refresh cache & sanity-check
          sudo fc-cache -fv
          fc-match "Host Grotesk"   # → HostGrotesk-Regular.ttf

      - run: uv sync --group docs
      - run: uv run mkdocs gh-deploy --force
